### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "marcos",
    "email": "marcos@gmail.com",
    "password": "qwerty00"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "willian@gmail.com",
    "password": "bananinha"
}

### 3) Create product
POST http://localhost:3003/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTI3Mzk5NiwiZXhwIjoxNjYxMzYwMzk2fQ.JYzYNtaOFBIvj4BS6lERXaUTwjeLGw6hgDzHmUIG6ss
Content-Type: application/json

{
    "name": "carambola",
    "tag": "[neutro,balada]"
}

### 4) Get products
GET http://localhost:3003/products

### 5) Get search products by id or name
GET http://localhost:3003/products/search?q=8360



### 6) Edit product
PUT http://localhost:3003/products/8360
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTM2MzMzMiwiZXhwIjoxNjYxNDQ5NzMyfQ.ifETZL5hRXZn4VOQ_LwapKUJ-O6L_DfwkI6ToLcB77Q
Content-Type: application/json

{
    "id":"333",
    "name": "vestido",
    "tag":"neutro"
}
### 7) Delete product
DELETE http://localhost:3003/products/716d2bc5-f409-4e64-b910-cdf05a4660ef
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTM2MzMzMiwiZXhwIjoxNjYxNDQ5NzMyfQ.ifETZL5hRXZn4VOQ_LwapKUJ-O6L_DfwkI6ToLcB77Q