### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "willian",
    "email": "willian@email.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "willian@gmail.com",
    "password": "bananinha"
}

### 3) Get all users
GET http://localhost:3003/users?search=wi
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTk4MTI1NCwiZXhwIjoxNjYwMDY3NjU0fQ.Pz-dcVOsrPz6UzZV-vOFRuCJt1O022I_lw5FG_mX_Ko

### 4) Delete user
DELETE http://localhost:3003/users/f03017bb-2c08-4cdc-bb63-7fbd7cebe01f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTk4MDU4MCwiZXhwIjoxNjYwMDY2OTgwfQ.O0pjVhWy6Yf9MiUcZyOi-xKIihyxuN-p12eweR3R87I