### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "will",
    "email": "will@gmail.com",
    "password": "will88"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Create show
POST http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxZTNjY2EyLTRlNTYtNGFmOS05OGMxLWY1NGNhNTg5YmM0NiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA3NTM0MDMsImV4cCI6MTY2MDgzOTgwM30.q8KV24Q5gC6S75K3AEcJLpGK8SGOpezKhwIN3LONVaI
Content-Type: application/json

{
    "band": "U2",
    "start_at": "2022/08/17"
}

### 4) Get shows
GET http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDc1NjUxMywiZXhwIjoxNjYwODQyOTEzfQ.j1_z5nPUE4JzdlLSvNBJbIf-OIGZ59Z4wpepQGZ5FFs